### ISSUE TITLE
Iosevka Extended

### ISSUE THREAD

**Issue by mbana** [peterwu/copr-iosevka#1]
Can you please add this font to the package?

References:

* https://typeof.net/Iosevka/ -> Iosevka Extended
* https://fontlibrary.org/en/font/iosevka-extended

**Comment by peterwu** [comment]
I believe extended variants are already included. E.g. iosevka-fonts-8.0.2-1.fc34.noarch.rpm
`rpm -ql iosevka-fonts` reports:

```
/usr/share/doc/iosevka-fonts
/usr/share/doc/iosevka-fonts/README.md
/usr/share/fonts/iosevka-fonts/iosevka-bold.ttf
/usr/share/fonts/iosevka-fonts/iosevka-bolditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-boldoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extended.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedbold.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedbolditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedboldoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedextrabold.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedextrabolditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedextraboldoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedextralight.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedextralightitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedextralightoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedheavy.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedheavyitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedheavyoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendeditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedlight.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedlightitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedlightoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedmedium.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedmediumitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedmediumoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedsemibold.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedsemibolditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedsemiboldoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedthin.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedthinitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extendedthinoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extrabold.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extrabolditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extraboldoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extralight.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extralightitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-extralightoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-heavy.ttf
/usr/share/fonts/iosevka-fonts/iosevka-heavyitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-heavyoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-italic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-light.ttf
/usr/share/fonts/iosevka-fonts/iosevka-lightitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-lightoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-medium.ttf
/usr/share/fonts/iosevka-fonts/iosevka-mediumitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-mediumoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-oblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-regular.ttf
/usr/share/fonts/iosevka-fonts/iosevka-semibold.ttf
/usr/share/fonts/iosevka-fonts/iosevka-semibolditalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-semiboldoblique.ttf
/usr/share/fonts/iosevka-fonts/iosevka-thin.ttf
/usr/share/fonts/iosevka-fonts/iosevka-thinitalic.ttf
/usr/share/fonts/iosevka-fonts/iosevka-thinoblique.ttf
/usr/share/licenses/iosevka-fonts
/usr/share/licenses/iosevka-fonts/LICENSE.md
```

**Comment by mbana** [comment]
For some reason I cannot select `iosevka-term-extended.ttf` in Gnome Terminal, please see this screenshot:



> I believe extended variants are already included. E.g. iosevka-fonts-8.0.2-1.fc34.noarch.rpm
> `rpm -ql iosevka-fonts` reports:
> 
> ```
> /usr/share/doc/iosevka-fonts
> /usr/share/doc/iosevka-fonts/README.md
> /usr/share/fonts/iosevka-fonts/iosevka-bold.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-bolditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-boldoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extended.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedbold.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedbolditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedboldoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedextrabold.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedextrabolditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedextraboldoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedextralight.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedextralightitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedextralightoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedheavy.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedheavyitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedheavyoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendeditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedlight.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedlightitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedlightoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedmedium.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedmediumitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedmediumoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedsemibold.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedsemibolditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedsemiboldoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedthin.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedthinitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extendedthinoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extrabold.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extrabolditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extraboldoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extralight.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extralightitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-extralightoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-heavy.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-heavyitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-heavyoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-italic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-light.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-lightitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-lightoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-medium.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-mediumitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-mediumoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-oblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-regular.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-semibold.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-semibolditalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-semiboldoblique.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-thin.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-thinitalic.ttf
> /usr/share/fonts/iosevka-fonts/iosevka-thinoblique.ttf
> /usr/share/licenses/iosevka-fonts
> /usr/share/licenses/iosevka-fonts/LICENSE.md
> ```

For some reason I cannot select `iosevka-term-extended.ttf` in Gnome Terminal, please see this screenshot:

![iosevka-term-extended ttf](https://user-images.githubusercontent.com/22658/127769325-c4352b7a-0548-46f1-85ce-4cbb94f3fabd.png)

**Comment by peterwu** [comment]
If `fc-list | grep Iosevka` reports the extended ones correctly, then it is a problem on Gnome Terminal. For some reason, it doesn't discover all the fonts installed in your system.

I have 2 workarounds:
1. Switch to another terminal emulator that does discover the fonts correctly. I personally use [Alacritty](https://github.com/alacritty/alacritty) but I hear good stories about [kitty](https://github.com/kovidgoyal/kitty), too. They're both available in Fedora.
2. Edit your fonts.conf file to designate an extended font to monospace. In your `~/.config/fontconfig/fonts.conf` file, you can do something as follows and then have Gnome Terminal pick it up as Monospace. Apparently, this affects all applications that use Monospace font.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test name="family" qual="any">
      <string>monospace</string>
    </test>
    <edit binding="strong" mode="prepend" name="family">
      <string>Iosevka Extended</string>
    </edit>
  </match>
</fontconfig>
```
