### ISSUE TITLE
Update Required for Iosevka Package Scripts Due to Filename Convention Change in Version 28

### ISSUE THREAD

**Issue by be5invis** [peterwu/copr-iosevka#5]
Hello maintainers of the `copr-iosevka`,

I am the maintainer of the [Iosevka project](https://github.com/be5invis/Iosevka), a typeface family that many users enjoy through your package platform. I would like to bring to your attention an important change that will affect the packaging and distribution process for Iosevka.

As posted in our [recent notification](https://github.com/be5invis/Iosevka/issues/2029), starting from the next major release (version 28), **Iosevka's font file naming convention will change**. Specifically, filenames will now use PascalCase for family name and weight-width-slope suffix, replacing the previous lowercase convention. Samples include:

- The file `iosevka-curly-slab-semiboldextendeditalic.ttf` will now be `IosevkaCurlySlab-SemiBoldExtendedItalic.ttf`.
- The file `iosevka.ttc` will now be `Iosevka.ttc`.

### Impact on Package Definitions and Scripts:
1. **Download Scripts**: Please ensure that any scripts or automated workflows for downloading the Iosevka fonts are updated to use the new file naming scheme.
2. **Package and Publish Scripts**: Adjustments will be necessary in the packaging phase to include the fonts with the updated names.
3. **Installation and Uninstallation Scripts**: It is crucial that these scripts be carefully revised to account for the new filenames. This will prevent any conflicts due to the presence of old file versions and ensure that users are consistently served the latest fonts correctly. Please make sure that your script could properly remove the old version of the fonts in their old names, and install the new version of the fonts using the new names.

I urge you to update your package definitions and scripts at your earliest convenience to reflect these changes. Timely action on your part will play a pivotal role in providing a seamless update experience for users who rely on your platform for their font needs.

Should you require additional assistance or clarification regarding the new filename convention, please feel free to ask. I am more than willing to collaborate and facilitate this transition.

Thank you for your attention to this matter, and I look forward to continuing our collaboration to serve the Iosevka user community.

Best regards,
Renzhi Li aka _be5invis_

**Comment by peterwu** [comment]
closed as per commit: a98af5df656e2fa9db56cd5b65e24139efd080b7

**Comment by be5invis** [comment]
@peterwu Make sure that you've tested that upgrading from an old version will properly remove old font files under old names and install the fonts under new name.

**Comment by peterwu** [comment]
When updating the relevant rpms, dnf/yum will remove the old version that contains the old files before installing the new rpm that contains the new files.
